services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - DATABASE_URL=sqlite:///./data/system.db
      - CORS_ORIGINS=http://localhost:6000,http://localhost:80
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - solo-leveling-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:6000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:8200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - solo-leveling-network

  # Development frontend with rollup fix
  frontend-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:6000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:8200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - solo-leveling-network
    profiles:
      - dev

  # Optional: Add Ollama for AI features (uncomment if needed)
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - solo-leveling-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

volumes:
  backend_data:
  # ollama_data:

networks:
  solo-leveling-network:
    driver: bridge
